#!/bin/bash

cols=$(tput cols)
lines=$(tput lines)
numcols=$(((cols-12)/2))
numlines=$((lines/2))

tput civis

while true; do
    clear
    tput cup $numlines $numcols
    printf '\e[31m%s\e[0m' [ $(date +%H:%M:%S) ]
    sleep 1
done

trap "tput cnorm" INT
